### PR TITLE
Fix path fish

### PR DESCRIPTION
**Pull request by cjappl**
## Check list

- [x] I have performed a self-review of my code
- [x] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Description

Getting up to parity with zsh version #58 

Also fixed a bunch of issues the fish side of things had with whitespace! so glad I checked this out, I was not handling things correctly.

## Type of change

- [x] Bug fix
- [x] New feature
- [x] Refactor

## Test environment

- Shell
    - [ ] bash
    - [ ] zsh 
    - [x] fish 
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:

### CODE REVIEW

**Comment by cjappl** [comment]
@wfxr  tagging you to take a look, but merging and closing. Thanks for the example!

In the future, if it's easy, providing an example like that is super helpful to make sure I'm implementing the right thing! That would be very appreciated :) Your example helped me catch a bunch of bugs in my original implementation I didn't realize.

Cheers!

**Comment by wfxr** [comment]
@cjappl OK. I will try to add more descriptions when I change the code. I notice that you fixed more bugs about white space. I will sync later.

**Comment by cjappl** [comment]
That would be great :)

Yeah I noticed there were a few more things going on.

Maybe at some point it would make sense to set up a "test repo" and a few
scripts to get files in certain states so we can make sure everything is
working right! May be good as a kind of "unit test"

**Comment by wfxr** [comment]
@cjappl Agree with you. But I don't have any good ideas on doing unit testing based on fzf. Maybe we have to use fzf's sdk to do this, just like fzf's own tests. That would be more troublesome. I will try it when I have enough time.

**Comment by cjappl** [comment]
Yeah, it's hard to say what the best way would be. I'll also investigate
FZF's tests and see what they have!

**Pull request merged**
