### PR TITLE
Fish shell support

### PR DESCRIPTION
**Pull request by cjappl**
Hi @wfxr,

I opened #42 but had some time on my hands so figured I'd take it on.

I'd love someone else to test this out, but it is working great on my end! You'll notice it looks very familiar to zsh/sh.

The only functionality I added was checking for fzf before sourcing, at the very top of the file

### CODE REVIEW

**Comment by cjappl** [comment]
I'd also be happy to update the README with a follow on commit if you determine this is something you want for your plugin :)

**Comment by wfxr** [comment]
Hi @cjappl Thank you for doing so much valuable work.

You may have noticed that `bash` version and `zsh` version share one single file. But for `fish` it is hard to achieve the same compatibility #18 . I don't want to maintain two codes with the same function but different implementations. This is why the `fish` support has not been implemented. 

But if you are willing to do long-term maintenance on the `fish` part (I have not used `fish`), I will be glad to merge it.

**Comment by cjappl** [comment]
I would be more than happy to help do maintenance on the fish part! I just turned my settings to "Watch" this project.

If you ever add a feature to the project, and can't figure out how to do it in fish or don't want to put in the time, please tag me in an issue and I can implement it!

Once you close this, I will update the README with appropriate info for fish. Excited to be working with you :)

**Comment by wfxr** [comment]
I have already added you as a collaborator. Thank you again for your contribution. :)

**Comment by cjappl** [comment]
Please file a new issue with the appropriate information including the fish
version. This is a closed issue

**Pull request merged**
