### PR TITLE
Add cherry-pick support

### PR DESCRIPTION
**Pull request by jsfaint**
## Check list

- [x] I have performed a self-review of my code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Type of change

- [ ] Bug fix
- [x] New feature
- [ ] Refactor
- [ ] Breaking change
- [x] Documentation change

## Test environment

- Shell
    - [x] bash
    - [x] zsh 
    - [ ] fish 
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

### CODE REVIEW

**Comment by wfxr** [comment]
@jsfaint Good enhancement. Thank you!

**Comment by jsfaint** [comment]
Sorry, I'm  not familiar with fish, so the fish support is not implemented. 😄

**Comment by wfxr** [comment]
@jsfaint Not a problem.  It's @cjappl's show time. :) 

BTW I did a minor refactor in https://github.com/wfxr/forgit/commit/13ca262e67b3f610c9b3f42d9dc821e5bd0ecd3b to make the ouput more uniform with other commands.

**Comment by jsfaint** [comment]
@wfxr Got it, thanks

**Comment by cjappl** [comment]
Thanks for your contribution!

Hopefully will get around to the fish portion this weekend :)

Hope everyone is staying safe and healthy!

**Comment by jsfaint** [comment]
You, too!
Stay home, stay safe

**Pull request merged**
