### PR TITLE
Add variable "forgit_extract_sha"

### PR DESCRIPTION
**Pull request by carlfriedrich**
This was a requested change from @cjappl as part of #219. Since we're not merging that PR, I'm submitting this separately, because I find it really useful for the code consistency.

There was also a tiny bug left for `git::cherry_pick`, where the SHA was not correctly parsed if `FORGIT_LOG_GRAPH_ENABLE` was set to false. I fixed this on the way, since it was the only command that parsed the SHA differently than the other commands.

I also included the `tr -d [:space:]` part in the variable, which is only used for copying the SHA to the clipboard but shouldn't cause trouble in the other use cases. @wfxr Can you check if copying still works correctly?

## Check list

- [x] I have performed a self-review of my code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Type of change

- [ ] Bug fix
- [ ] New feature
- [x] Refactor
- [ ] Breaking change
- [ ] Documentation change

## Test environment

- Shell
    - [x] bash
    - [x] zsh
    - [x] fish
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

### CODE REVIEW

**Comment by cjappl** [comment]
You're a PR machine!! Also really appreciate you doing both shells at once, 👍 👍 

change looks good to me, will leave it to @wfxr to officially approve

**Comment by carlfriedrich** [comment]
@cjappl Just trying to improve some piece of software that I really enjoy using. Won't be my last PR. :-)
And I really appreciate that you both are so supportive concerning external PRs. That's not the case on every open source project.

**Comment by cjappl** [comment]
Love it!

Hey the more work others do, the less wfxr and I need to do. ;)

“Many hands make light work”!! We really appreciate the submissions.

**Review by wfxr — APPROVED** [review]
LGTM!

**Comment by wfxr** [comment]
@carlfriedrich Thank you! This makes the code cleaner! I tested in zsh and it works good.

**Pull request merged**
