### PR TITLE
Fix for: ga preview not working with fish

### LINKED ISSUE #170: ga preview not working with fish
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

When using the latest version with fish, installed either with `fisher install wfxr/forgit` or `source (curl -sSL git.io/forgit-fish | psub)`, `ga` shows the following error.

```
fish: $\ is not a valid variable in fish.
        sed -e 's/^\\\"//' -e 's/\\\"\$//'  # removes surrounding quotes
                                      ^
```

This is on a folder that contains a git repository.

similar to #168

### PR DESCRIPTION
**Pull request by cjappl**
Closes #170 

## Check list

- [x] I have performed a self-review of my code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Type of change

- [x] Bug fix

## Test environment

- Shell
    - [x] fish
- OS
    - [x] Mac OS X

### CODE REVIEW

**Comment by cjappl** [comment]
@wfxr would you double check this. Is there a case in which we expect this to be surrounded by double quotes? I removed it and there was no issue, so wondering why it was there in the first place

**Comment by wfxr** [comment]
> @wfxr would you double check this. Is there a case in which we expect this to be surrounded by double quotes? I removed it and there was no issue, so wondering why it was there in the first place 

When the file path contains spaces like this:
```sh
touch foo.txt 'foo bar.txt'
git status -s
```

**Comment by cjappl** [comment]
Thanks I’ll double check this tomorrow morning and make sure it works.

**Comment by cjappl** [comment]
Alright, this breaks spaces in file names but I've tried for a few hours and I can't fix it.

I'm going to reach out for help on the fish project page and see if anyone can see what my issue is. Something with the way fish deals with single and double quotes. I will keep you posted

**Comment by cjappl** [comment]
Merging this for now, as I think this problem is bigger than the files with spaces in them issue

**Pull request merged**
