### PR TITLE
Git rebase for fish

### PR DESCRIPTION
**Pull request by cjappl**
## Check list

- [x] I have performed a self-review of my code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Type of change

- [ ] Bug fix
- [x] New feature
- [ ] Refactor
- [ ] Breaking change
- [ ] Documentation change

## Test environment

- Shell
    - [ ] bash
    - [ ] zsh 
    - [x] fish 
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:

### CODE REVIEW

**Comment by cjappl** [comment]
@wfxr again I'm not sure why there are so many commits here.... 

Anything I can do to get this down to the one commit I made?

**Comment by wfxr** [comment]
@cjappl Have you run `git rebase -i` or `grb` locally before pushing to your repo? `git rebase -i` will update every selected commit hashes even if you do nothing but quitting the editor.

**Comment by wfxr** [comment]
Since you are a collaborator of this repo, I suggest you work on this original repo. you can checkout a new branch  If you do some changes need to be reviewd

**Comment by cjappl** [comment]
Good idea, I'll try to work directly when I need to from now on. Probably easier than untangling mine

Closing in favor of #124

**Pull request closed without merging**
