### PR TITLE
Reset color in git format after each line so next line does not get a…

### PR DESCRIPTION
**Pull request by 7ocb**
…ffected

## Check list

- [ ] I have performed a self-review of my code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Breaking change
- [ ] Documentation change

## Test environment

- Shell
    - [ ] bash
    - [x] zsh 
    - [ ] fish 
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

### CODE REVIEW

**Comment by cjappl** [comment]
Please update these in the fish file too, should be done exactly as you've done for zsh

**Comment by 7ocb** [comment]
@cjappl done.

**Comment by cjappl** [comment]
lgtm! Passing to @wfxr for final review

**Review by wfxr — APPROVED** [review]

**Comment by wfxr** [comment]
LGTM. Thanks for your contribution! @7ocb

**Pull request merged**
