### PR TITLE
Add bash completions for forgit functions and aliases

### PR DESCRIPTION
**Pull request by carlfriedrich**
## Check list

- [x] I have performed a self-review of my code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Description

This is a follow-up to #235 and adds bash completion to the plugin functions and aliases.

## Type of change

- [ ] Bug fix
- [x] New feature
- [ ] Refactor
- [ ] Breaking change
- [ ] Documentation change

## Test environment

- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

### CODE REVIEW

**Review by cjappl — APPROVED** [review]
Seems reasonable to me!

**Comment by dagadbm** [comment]
Yes please :D 

I was just about to suggest this because for sure it is really important to have

**Comment by dagadbm** [comment]
I forgot to ask if this will work for zsh or not

**Comment by carlfriedrich** [comment]
@dagadbm No, these are completions for bash only. I am not familiar with the zsh completion mechanism. Contributions for this are very welcome!

**Pull request merged**
