### PR TITLE
fix shell error in forgit.plugin.zsh

### PR DESCRIPTION
**Pull request by laur89**
caused by https://github.com/wfxr/forgit/commit/325e98cd03c71d7e280b7259ff7793cec0afd726#diff-b3f00b3beaf9e81cc8bee82da7fc86faR6

### CODE REVIEW

**Comment by cjappl** [comment]
I'm not sure I see the error here, when I run it unchanged:

```
CJAPPL-MBP% source forgit.plugin.zsh
[Warn] FZF not found and is requried for forgit
CJAPPL-MBP% echo $?
1
```

Can you describe what error you're seeing? These commands look equivalent

**Comment by laur89** [comment]
Did you try it in bash?

**Comment by cjappl** [comment]
Ah! Yes, definitely see it! Thanks for the clarity. This LGTM, I'll merge it now because it's core to the plugin actually working @wfxr

**Comment by cjappl** [comment]
Thanks for the help @laur89, my inexperience with bash is showing ;)

**Comment by cjappl** [comment]
Tested and confirmed this fix on my machine with both zsh and sh

**Comment by wfxr** [comment]
@cjappl @laur89 Thanks. :lgtm:

**Pull request merged**
