### PR TITLE
FORGIT_BAT_OPTS to add options to bat

### PR DESCRIPTION
**Pull request by mirsella**
## Check list

- [x] I have performed a self-review of my code
- [] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Description

before the default option for bat where just `--color=always`, but now if FORGIT_BAT_OPTION is set it will use add the value of the variable to bat command.
for me, I want to use the following option to bat : `-pp --color=always --theme "Monokai Extended Origin"`
which I can use by setting the following in my zshrc : 
`export FORGIT_BAT_OPTION='-pp --color=always --theme="Monokai Extended Origin"'`

## Type of change

- [ ] Bug fix
- [x] New feature
- [ ] Refactor
- [ ] Breaking change
- [ ] Documentation change

## Test environment

- Shell
    - [x] bash
    - [x] zsh 
    - [x] fish 
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

### CODE REVIEW

**Comment by mirsella** [comment]
my last commit "removed curly brace in for fish" was supposed to be "removed curly brace in ${} for fish" but zsh took it has empty haha

**Comment by cjappl** [comment]
At the very least you should update the naming of the variable to be consistent with the rest of the code base,

should be:

FORGIT_BAT_OPTS

**Comment by mirsella** [comment]
I'll change the var name when I get home

**Comment by mirsella** [comment]
up

**Comment by cjappl** [comment]
Need to update the README as well, then it's up to @wfxr  to determine if this should go in!

Thanks for the quick edit :)

**Comment by mirsella** [comment]
thank you :)

**Comment by wfxr** [comment]
@mirsella @cjappl Thanks for work on this.

I think It’s overkill to add an option specifically for `bat` since it is only an optional pager used in `forgit::ignore`.
But I am not opposed to adding a custon pager option for `forgit::ignore`, such as `FORGIT_IGNORE_PAGER`, just like `FORGIT_SHOW_PAGER` and `FORGIT_DIFF_PAGER`. This would be more consistent and can also solve the problem someone wants to use pager other than `cat` or `bat` to render the `gitignore` content.

**Review by wfxr — CHANGES_REQUESTED** [review]
better to add an option `FORGIT_IGNORE_PAGER` for forgit::ignore

**Comment by mirsella** [comment]
I'll update it thanks

**Comment by mirsella** [comment]
should be good, i hope i didn't forget a change somewhere

**Comment by wfxr** [comment]
@mirsella Can be merged. Thanks for your contribution!

**Pull request merged**
