### PR TITLE
Handle .gitconfig pager attribute.

### PR DESCRIPTION
**Pull request by vedang**
The existing script handles the `core.pager` attribute, but does not
account for the `pager` attribute in git-config. Tools like
`diff-highlight` which ship with git recommend using the `pager`
attribute, and provide beautiful diffs.

I've made minor changes in the script to use these configuration
parameters if they are defined.

Ref: https://github.com/git/git/tree/master/contrib/diff-highlight

## Check list

- [X] I have performed a self-review of my code : I do not use ZSH, so this is untested there, but it is a very small change. I request you to review it and decide on next steps.
- [X] I have commented my code in hard-to-understand areas: No comment needed
- [X] I have made corresponding changes to the documentation: No change in existing documentation

## Description

Description is part of the commit message above. This change lets me use diff-highlight tool to show beautiful diffs.

## Type of change

- [ ] Bug fix
- [X] New feature
- [ ] Refactor
- [ ] Breaking change
- [ ] Documentation change

## Test environment

- Shell
    - [X] bash
    - [ ] zsh 
    - [ ] fish 
- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

### CODE REVIEW

**Comment by wfxr** [comment]
@vedang Thank you. This would be a good improvement.

**Comment by cjappl** [comment]
Thanks! Will complete this on Monday

**Comment by cjappl** [comment]
Hi @vedang!

thanks for the great PR.

Just so I know that I've copied the behavior exactly, can you describe how you have your .gitconfig set up to have this functionality?

Is it just like in that link you sent, you have a section that is something like:

```
[pager]
	log = diff-highlight | less
	show = diff-highlight | less
	diff = diff-highlight | less
```

Also, would you add a screenshot of what the output of forgit looks like with this set up properly?

Thanks a lot!

**Comment by vedang** [comment]
Yes,

I have the pager section exactly as mentioned in the link (as you've copied
over)

I have the compaction heuristic diff config as well. I'll share the
relevant sections of ths gitconfig and the screenshots once I'm in front of
my computer.

/vedang
(Sent from my phone, please excuse brevity)

**Comment by cjappl** [comment]
Awesome thanks! Look forward to seeing the screenshot. I’ll get rolling on
this tomorrow

**Comment by vedang** [comment]
Hello! I know I'm late to this, but here is a screenshot and the relevant parts of my gitconfig: 
Screen Shot 2020-08-14 at 8 36 23 AM

```
[diff]
	compactionHeuristic = true
[pager]
	log = diff-highlight | less
	show = diff-highlight | less
	diff = diff-highlight | less
[interactive]
	diffFilter = diff-highlight
```

**Comment by cjappl** [comment]
Awesome! I think i got it all sorted, but I appreciate the follow up.

Thanks for contributing!

**Pull request merged**
