### PR TITLE
editBindings -  Be able to edit with Vim

### PR DESCRIPTION
**Pull request by ggsalas**
## Check list

- [x] I have performed a self-review of my code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Description

I have added actions to:
- forgit::log
  - ctrl-e: to Edit
- forgit::diff
  - ctrl-e: to Edit
  - ctrl-y: to copy file path
- forgit::stash::show
  - ctrl-e: to Edit

Also, I have added a header to remember the bindings

## Type of change

- [ ] Bug fix
- [x] New feature
- [ ] Refactor
- [ ] Breaking change
- [ ] Documentation change

## Test environment

- Shell
    - [ ] bash
    - [x] zsh 
    - [ ] fish 
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:

### CODE REVIEW

**Comment by wfxr** [comment]
Hi @ggsalas Thanks for your contribution. But I don't fully understand what the point of editing the logs produced by git is?

**Comment by ggsalas** [comment]
> Hi @ggsalas Thanks for your contribution. But I don't fully understand what the point of editing the logs produced by git is?

Hi @wfxr Some times I need to copy some part of the code. Currently, that is very difficult to do.

**Comment by cjappl** [comment]
Whether or not this feature is accepted, there should at the very least be a change to the README to document the new features

**Comment by wfxr** [comment]
Yes, I'm in favor of adding descriptions about the copy keybind into README. As for the `edit` function I think it's more suitable to be implemented by the command specific options such as `FORGIT_LOG_FZF_OPTS` and `FORGIT_DIFF_FZF_OPTS`. Maybe someone expected to edit the related files instead of the logs content.

**Pull request closed without merging**
