### PR TITLE
Detect unexported variables in fish correctly (Fix #289)

### LINKED ISSUE #289: Detection of unexported variables is incorrect in fish if the variable has an empty string value
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

In my `config.fish` I have:
```fish
set -x FORGIT_FZF_DEFAULT_OPTS "

--ansi
--height='80%'
--bind='alt-k:preview-up,alt-p:preview-up'
--bind='alt-j:preview-down,alt-n:preview-down'
--bind='ctrl-r:toggle-all'
--bind='ctrl-s:toggle-sort'
--bind='?:toggle-preview'
--bind='alt-w:toggle-preview-wrap'
--preview-window='right:60%'
+1

"
set -x FORGIT_GI_REPO_LOCAL ""
set -x FORGIT_GI_REPO_REMOTE "https://github.com/dvcs/gitignore"
set -x FORGIT_GI_TEMPLATES ""
```

Everytime I open a new fish shell I get
```
[Warn] Config options have to be exported in future versions of forgit.                                                                                       
[Warn] Please update your config accordingly:
```
The full message gets cut off by my prompt which is annoying but not forgit's fault.

Doing `set -x | grep FORGIT_` I can see all of those variables exported of course, so the question is why `set -x | grep -q "^$var "` in `forgit.plugin.fish` seems to fail

It seems to be due to the trailing whitespace in the argument to grep. `set -x | grep -q "^$var "` fails but `set -x | grep -q "^$var"`

When the variable's value is an empty string, the output of `set -x` does not have any trailing whitespace.

Unless there is some reason I am missing, simply removing the trailing whitespace from `grep -q "^$var "` should work

### PR DESCRIPTION
**Pull request by IndianBoy42**
## Check list

- [x] I have performed a self-review of my code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Description

See #289 for the complete details

## Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Breaking change
- [ ] Documentation change

## Test environment

- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

### CODE REVIEW

**Comment by cjappl** [comment]
Seems totally reasonable to me. Thanks for catching. Requested review from @carlfriedrich as well to make sure that tracks with his understanding.

I'll merge and close later in the week regardless. Thanks for the contribution

**Comment by carlfriedrich** [comment]
Hi @IndianBoy42, thanks for the catch! I think the reason for the space in the grep expression was to mark the end of the variable name. Otherwise `FORGIT_SOMETHING` would also match `FORGIT_SOMETHING_ELSE`, which is not what we want here.

So we actually need the space. We could, however, extend the expression to *also* match the variable name followed by the end of the line (`$`), which I assume is what you have in your case? Could you check that?

**Review by carlfriedrich — CHANGES_REQUESTED** [review]
Hi @IndianBoy42, thanks for the catch! I think the reason for the space in the grep expression was to mark the end of the variable name. Otherwise `FORGIT_SOMETHING` would also match `FORGIT_SOMETHING_ELSE`, which is not what we want here.

So we actually need the space. We could, however, extend the expression to *also* match the variable name followed by the end of the line (`$`), which I assume is what you have in your case? Could you check that?

**Comment by IndianBoy42** [comment]
> So we actually need the space. We could, however, extend the expression to _also_ match the variable name followed by the end of the line (`$`), which I assume is what you have in your case? Could you check that?

Oh, that makes sense, it makes me think `\b` for word boundary potentially matches the intent most closely

**Review by carlfriedrich — APPROVED** [review]
Seems reasonable to me! Leaving final approval and merge for @cjappl.

**Comment by cjappl** [comment]
Thanks for the submission @IndianBoy42

**Pull request merged**
