### PR TITLE
Attempt 2 to create a fish plugin

### PR DESCRIPTION
**Pull request by AoHiyuki**
## Check list

- [x] I have performed a self-review of my code
- [ ] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Description

Update on making this plugin work with Fisher. I combined all the code back like before and changed the README a bit. The short link will need to be fix since I can't generate a proper one.

## Type of change

- [ ] Bug fix
- [ ] New feature
- [x] Refactor
- [ ] Breaking change
- [x] Documentation change

## Test environment

- Shell
    - [ ] bash
    - [ ] zsh 
    - [x] fish 
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

### CODE REVIEW

**Comment by wfxr** [comment]
The commit history is messed up. Please wait for me to do a rebase.

**Comment by wfxr** [comment]
@AoHiyuki I did a minor changes based on your pr. Can you update and test if it works as expected?

**Comment by AoHiyuki** [comment]
2020-10-13-06:53:13_1461x503

Yeah it works.
Sorry for the history conflicts I tried to work around our previous issue and forgot to roll back HEAD.

**Comment by wfxr** [comment]
That's OK @AoHiyuki 

Thanks for your contribution!

**Comment by AoHiyuki** [comment]
I think we can close #116 or just let it be there if @cjappl wants to add more support on the future.

**Comment by AoHiyuki** [comment]
I just caught a minor issue. Didn't check things out thoroughly :(

`forgit.plugin.fish` appears in 2 places (even if it is just a symlink). So when installed with Fisher it will be copied to both conf.d and functions (the file in conf.d to ~/.config/fish/conf.d and the main file to ~/.config/fish/functions)

It works with no problems, but fish now will register a function named **forgit.plugin** (that doesn't do anything) since the file is there in the functions directory.

Is there an absolute reason you want to put the main file in root directory @wfxr ?

**Pull request merged**
