### PR TITLE
fix: forgit::log can not match files

### PR DESCRIPTION
**Pull request by ZenLian**
## Check list

- [x] I have performed a self-review of my code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Description

**Bug**: `glo -- files` should show specified files only, but instead it shows all changed files.
**Fix**: There is a redundent blank in sed regex.

## Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Breaking change
- [ ] Documentation change

## Test environment

- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

### CODE REVIEW

**Comment by carlfriedrich** [comment]
@ZenLian Thanks for your PR! We just merged a significant change which conflicts with your patch. Can you rebase this on current master?

**Comment by ZenLian** [comment]
@carlfriedrich Rebase done. Sorry for my late reply.

**Review by carlfriedrich — APPROVED** [review]
@ZenLian Thank you! I can confirm that your patch actually changes the behavior from "show all files in the diff" to "show only given files in the diff", and I think that the last one should be correct.

Since @wfxr originally implemented this in #85 I would leave the final approval to him.

**Comment by cjappl** [comment]
Seeing as @wfxr has been busy recently, I think we should consider merging this! What do you think @carlfriedrich ?

**Pull request merged**
