### PR TITLE
use fish to interpret preview command

### LINKED ISSUE #168: forgit add doesn't preview properly when user shell is bash and interactive shell is fish
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce
When I use `ga`, the preview doesn't work

image

This is because my user shell is bash and my interactive shell is fish. (This was necessary because fish can't read system config files: https://wiki.archlinux.org/title/Fish#Setting_fish_as_default_shell). fzf uses bash to interpret `$preview` which won't work because it is fish syntax.

The fix is to use fish to interpret `$preview` like so:
```diff
--- forgit_fix.fish	2021-11-26 09:33:13.403016477 +0530
+++ .config/fish/conf.d/forgit.plugin.fish	2021-11-26 09:33:47.813758484 +0530
@@ -102,12 +102,12 @@
     set preview "
         set file (echo {} | $extract_file)
         # exit
-        if test (git status -s -- \\\$file | grep '^??') # diff with /dev/null for untracked files
-            git diff --color=always --no-index -- /dev/null \\\$file | $forgit_diff_pager | sed '2 s/added:/untracked:/'
+        if test (git status -s -- \$file | grep '^??') # diff with /dev/null for untracked files
+            git diff --color=always --no-index -- /dev/null \$file | $forgit_diff_pager | sed '2 s/added:/untracked:/'
         else
-            git diff --color=always -- \\\$file | $forgit_diff_pager
+            git diff --color=always -- \$file | $forgit_diff_pager
         end
-    "
+        "
     set opts "
         $FORGIT_FZF_DEFAULT_OPTS
         -0 -m --nth 2..,..
@@ -116,7 +116,7 @@
     set files (git -c color.status=always -c status.relativePaths=true status -su |
         grep -F -e "$changed" -e "$unmerged" -e "$untracked" |
         sed -E 's/^(..[^[:space:]]*)[[:space:]]+(.*)\$/[\1]  \2/' |   # deal with white spaces internal to fname
-        env FZF_DEFAULT_OPTS="$opts" fzf --preview="fish -c \"$preview\"" |
+        env FZF_DEFAULT_OPTS="$opts" fzf --preview="$preview" |
         sh -c "$extract_file") # for rename case
 
     if test -n "$files"
@@ -544,3 +544,4 @@
     end
 
 end
+
```

This fixes the issue:

image

### PR DESCRIPTION
**Pull request by p00f**
fixes #168

## Check list

- [x] I have performed a self-review of my code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Description

See https://github.com/wfxr/forgit/issues/168#issue-1064088027

## Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Breaking change
- [ ] Documentation change

## Test environment

- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

### CODE REVIEW

**Comment by wfxr** [comment]
@p00f LGTM. Thanks for your contribution !

**Comment by cjappl** [comment]
This seems to be the root cause of #170 

I'm going to revert this change for now, as I feel this is a bit of a strange workflow.

Absolutely open to fixes for this, but unfortunately this one causes a big breakage on latest fish!!

**Comment by p00f** [comment]
@cjappl I applied this patch again, it works on fish 3.3.1 :/

**Comment by cjappl** [comment]
Can you try it in a shell with both interactive and user shells are fish?

That was my config in which it wasn’t working, see the details in #170

Let me know. Definitely down to get to the bottom of this :)

**Pull request merged**
