### PR TITLE
Glo format

### PR DESCRIPTION
**Pull request by rlanore**
## Check list

- [x] I have performed a self-review of my code
- [ ] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Description
Add a way to personalized git log format. Personaly i prefer something like

`%C(auto)%h%d %s %C(blue)%an %C(green)%C(bold)%cr`

I work with black background screen. so black on blackl is not usefull. 

## Type of change

- [ ] Bug fix
- [x] New feature
- [ ] Refactor
- [ ] Breaking change
- [ ] Documentation change

## Test environment

- Shell
    - [x] bash
    - [x] zsh 
    - [ ] fish 
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:

### CODE REVIEW

**Comment by wfxr** [comment]
Mostly LGTM. I added some minor changes.

**Comment by wfxr** [comment]
@cjappl I will mark the PRs that needs to be synchronized to fish. You can easily filter them by the `to-sync-fish` lable (once it's done you can remove it).

Thank you again for your efforts to help me maintain the project :heart:

**Comment by cjappl** [comment]
Perfect!! That makes it a lot easier :) I will get to these soon.

**Comment by cjappl** [comment]
Fish synced

**Pull request merged**
